export const subscriptionTemplates = [
  {
    name: "Netflix",
    logo: "https://cdn.simpleicons.org/netflix/E50914",
    category: "Entertainment",
    plans: [
      { name: "Mobile", amount: 149, billingCycle: "MONTHLY" },
      { name: "Basic", amount: 199, billingCycle: "MONTHLY" },
      { name: "Standard", amount: 499, billingCycle: "MONTHLY" },
      { name: "Premium", amount: 649, billingCycle: "MONTHLY" },
    ],
  },
  {
    name: "Prime Video",
    logo: "https://www.google.com/s2/favicons?domain=primevideo.com&sz=128",
    category: "Entertainment",
    plans: [
      { name: "Monthly", amount: 299, billingCycle: "MONTHLY" },
      { name: "Yearly", amount: 1499, billingCycle: "YEARLY" },
    ],
  },
  {
    name: "JioHotstar",
    logo: "https://www.google.com/s2/favicons?domain=hotstar.com&sz=128",
    category: "Entertainment",
    plans: [
      { name: "Mobile", amount: 149, billingCycle: "QUARTERLY" },
      { name: "Super", amount: 299, billingCycle: "QUARTERLY" },
      { name: "Premium", amount: 299, billingCycle: "MONTHLY" },
      { name: "Premium", amount: 1499, billingCycle: "YEARLY" },
    ],
  },
  {
    name: "Chess.com",
    logo: "https://cdn.simpleicons.org/chessdotcom/81B64C",
    category: "Gaming",
    plans: [
      { name: "Gold", amount: 399, billingCycle: "MONTHLY" },
      { name: "Gold", amount: 2999, billingCycle: "YEARLY" },
      { name: "Platinum", amount: 599, billingCycle: "MONTHLY" },
      { name: "Platinum", amount: 4999, billingCycle: "YEARLY" },
      { name: "Diamond", amount: 999, billingCycle: "MONTHLY" },
      { name: "Diamond", amount: 7999, billingCycle: "YEARLY" },
    ],
  },
  {
    name: "YouTube Premium",
    logo: "https://cdn.simpleicons.org/youtube/FF0000",
    category: "Entertainment",
    plans: [
      { name: "Individual", amount: 149, billingCycle: "MONTHLY" },
      { name: "Student", amount: 89, billingCycle: "MONTHLY" },
      { name: "Family", amount: 299, billingCycle: "MONTHLY" },
      { name: "Individual", amount: 1490, billingCycle: "YEARLY" },
    ],
  },
  {
    name: "Spotify",
    logo: "https://cdn.simpleicons.org/spotify/1DB954",
    category: "Music",
    plans: [
      { name: "Mini", amount: 7, billingCycle: "MONTHLY" },
      { name: "Individual", amount: 119, billingCycle: "MONTHLY" },
      { name: "Duo", amount: 149, billingCycle: "MONTHLY" },
      { name: "Family", amount: 179, billingCycle: "MONTHLY" },
      { name: "Student", amount: 59, billingCycle: "MONTHLY" },
      { name: "Individual", amount: 1189, billingCycle: "YEARLY" },
    ],
  },
  {
    name: "ChatGPT",
    logo: "https://www.google.com/s2/favicons?domain=openai.com&sz=128",
    category: "AI",
    plans: [
      { name: "Plus", amount: 1999, billingCycle: "MONTHLY" },
      { name: "Pro", amount: 19900, billingCycle: "MONTHLY" },
    ],
  },
  {
    name: "Gemini",
    logo: "https://cdn.simpleicons.org/googlegemini/8E75B2",
    category: "AI",
    plans: [
      { name: "Google AI Pro", amount: 1950, billingCycle: "MONTHLY" },
      { name: "Google AI Pro", amount: 19500, billingCycle: "YEARLY" },
      { name: "Google AI Ultra", amount: 24999, billingCycle: "MONTHLY" },
    ],
  },
  {
    name: "Claude",
    logo: "https://www.google.com/s2/favicons?domain=claude.ai&sz=128",
    category: "AI",
    plans: [
      { name: "Pro", amount: 1999, billingCycle: "MONTHLY" },
      { name: "Max", amount: 9900, billingCycle: "MONTHLY" },
      { name: "Team", amount: 2999, billingCycle: "MONTHLY" },
    ],
  },
  {
    name: "Perplexity",
    logo: "https://cdn.simpleicons.org/perplexity/20B8CD",
    category: "AI",
    plans: [
      { name: "Pro", amount: 1999, billingCycle: "MONTHLY" },
      { name: "Pro", amount: 19900, billingCycle: "YEARLY" },
    ],
  },
  {
    name: "Sony LIV",
    logo: "https://www.google.com/s2/favicons?domain=sonyliv.com&sz=128",
    category: "Entertainment",
    plans: [
      { name: "Mobile", amount: 299, billingCycle: "YEARLY" },
      { name: "LIV Premium", amount: 399, billingCycle: "QUARTERLY" },
      { name: "LIV Premium", amount: 999, billingCycle: "YEARLY" },
    ],
  },
  {
    name: "ZEE5",
    logo: "https://www.google.com/s2/favicons?domain=zee5.com&sz=128",
    category: "Entertainment",
    plans: [
      { name: "Premium", amount: 199, billingCycle: "MONTHLY" },
      { name: "Premium", amount: 599, billingCycle: "YEARLY" },
      { name: "Premium 4K", amount: 1499, billingCycle: "YEARLY" },
    ],
  },
  {
    name: "X Premium",
    logo: "https://www.google.com/s2/favicons?domain=x.com&sz=128",
    category: "Social",
    plans: [
      { name: "Basic", amount: 243, billingCycle: "MONTHLY" },
      { name: "Basic", amount: 2590, billingCycle: "YEARLY" },
      { name: "Premium", amount: 650, billingCycle: "MONTHLY" },
      { name: "Premium", amount: 6800, billingCycle: "YEARLY" },
      { name: "Premium Plus", amount: 1300, billingCycle: "MONTHLY" },
      { name: "Premium Plus", amount: 13600, billingCycle: "YEARLY" },
    ],
  },
  {
    name: "Figma",
    logo: "https://cdn.simpleicons.org/figma/F24E1E",
    category: "Design",
    plans: [
      { name: "Professional", amount: 1299, billingCycle: "MONTHLY" },
      { name: "Professional", amount: 12499, billingCycle: "YEARLY" },
      { name: "Organization", amount: 3999, billingCycle: "MONTHLY" },
      { name: "Organization", amount: 39999, billingCycle: "YEARLY" },
    ],
  },
  {
    name: "Adobe Photoshop",
    logo: "https://www.google.com/s2/favicons?domain=adobe.com&sz=128",
    category: "Design",
    plans: [
      { name: "Photoshop", amount: 1675, billingCycle: "MONTHLY" },
      { name: "Photoshop", amount: 19188, billingCycle: "YEARLY" },
    ],
  },
  {
    name: "Adobe Creative Cloud",
    logo: "https://www.google.com/s2/favicons?domain=creativecloud.adobe.com&sz=128",
    category: "Design",
    plans: [
      { name: "Creative Cloud All Apps", amount: 4230, billingCycle: "MONTHLY" },
      { name: "Creative Cloud All Apps", amount: 50800, billingCycle: "YEARLY" },
      { name: "Student All Apps", amount: 1596, billingCycle: "MONTHLY" },
      { name: "Student All Apps", amount: 19152, billingCycle: "YEARLY" },
    ],
  },
  {
    name: "Adobe Premiere Pro",
    logo: "https://www.google.com/s2/favicons?domain=adobe.com&sz=128",
    category: "Video Editing",
    plans: [
      { name: "Premiere Pro", amount: 1675, billingCycle: "MONTHLY" },
      { name: "Premiere Pro", amount: 19188, billingCycle: "YEARLY" },
    ],
  },
  {
    name: "Adobe Illustrator",
    logo: "https://www.google.com/s2/favicons?domain=adobe.com&sz=128",
    category: "Design",
    plans: [
      { name: "Illustrator", amount: 1675, billingCycle: "MONTHLY" },
      { name: "Illustrator", amount: 19188, billingCycle: "YEARLY" },
    ],
  },
  {
    name: "Apple TV+",
    logo: "https://cdn.simpleicons.org/appletv/FFFFFF",
    category: "Entertainment",
    plans: [
      { name: "Monthly", amount: 99, billingCycle: "MONTHLY" },
      { name: "Yearly", amount: 999, billingCycle: "YEARLY" },
    ],
  },
  {
    name: "Lionsgate Play",
    logo: "https://www.google.com/s2/favicons?domain=lionsgateplay.com&sz=128",
    category: "Entertainment",
    plans: [
      { name: "Monthly", amount: 149, billingCycle: "MONTHLY" },
      { name: "Yearly", amount: 699, billingCycle: "YEARLY" },
    ],
  },
  {
    name: "Crunchyroll",
    logo: "https://cdn.simpleicons.org/crunchyroll/F47521",
    category: "Anime",
    plans: [
      { name: "Fan", amount: 79, billingCycle: "MONTHLY" },
      { name: "Mega Fan", amount: 99, billingCycle: "MONTHLY" },
      { name: "Mega Fan", amount: 999, billingCycle: "YEARLY" },
    ],
  },
  {
    name: "Filmora",
    logo: "https://cdn.simpleicons.org/wondershare/00B2A9",
    category: "Video Editing",
    plans: [
      { name: "Monthly", amount: 999, billingCycle: "MONTHLY" },
      { name: "Annual", amount: 4999, billingCycle: "YEARLY" },
      { name: "Perpetual", amount: 7999, billingCycle: "YEARLY" },
    ],
  },
  {
    name: "Discord Nitro",
    logo: "https://cdn.simpleicons.org/discord/5865F2",
    category: "Communication",
    plans: [
      { name: "Nitro Basic", amount: 99, billingCycle: "MONTHLY" },
      { name: "Nitro Basic", amount: 999, billingCycle: "YEARLY" },
      { name: "Nitro", amount: 249, billingCycle: "MONTHLY" },
      { name: "Nitro", amount: 2499, billingCycle: "YEARLY" },
    ],
  },
  {
    name: "Zoom",
    logo: "https://cdn.simpleicons.org/zoom/0B5CFF",
    category: "Productivity",
    plans: [
      { name: "Pro", amount: 1199, billingCycle: "MONTHLY" },
      { name: "Pro", amount: 11999, billingCycle: "YEARLY" },
      { name: "Business", amount: 1599, billingCycle: "MONTHLY" },
      { name: "Business", amount: 15999, billingCycle: "YEARLY" },
    ],
  },
  {
    name: "Hostinger",
    logo: "https://cdn.simpleicons.org/hostinger/673DE6",
    category: "Hosting",
    plans: [
      { name: "Premium Web Hosting", amount: 149, billingCycle: "MONTHLY" },
      { name: "Business Web Hosting", amount: 249, billingCycle: "MONTHLY" },
      { name: "Cloud Startup", amount: 699, billingCycle: "MONTHLY" },
      { name: "Premium Web Hosting", amount: 1788, billingCycle: "YEARLY" },
      { name: "Business Web Hosting", amount: 2988, billingCycle: "YEARLY" },
      { name: "Cloud Startup", amount: 8388, billingCycle: "YEARLY" },
    ],
  },
  {
    name: "GoDaddy",
    logo: "https://cdn.simpleicons.org/godaddy/1BDBDB",
    category: "Hosting",
    plans: [
      { name: "Basic Hosting", amount: 199, billingCycle: "MONTHLY" },
      { name: "Deluxe Hosting", amount: 299, billingCycle: "MONTHLY" },
      { name: "Ultimate Hosting", amount: 449, billingCycle: "MONTHLY" },
      { name: "Basic Hosting", amount: 2388, billingCycle: "YEARLY" },
      { name: "Deluxe Hosting", amount: 3588, billingCycle: "YEARLY" },
      { name: "Ultimate Hosting", amount: 5388, billingCycle: "YEARLY" },
      { name: "Domain Renewal", amount: 999, billingCycle: "YEARLY" },
    ],
  },
  {
    name: "Canva Pro",
    logo: "https://www.google.com/s2/favicons?domain=canva.com&sz=128",
    category: "Design",
    plans: [
      { name: "Pro", amount: 500, billingCycle: "MONTHLY" },
      { name: "Pro", amount: 4000, billingCycle: "YEARLY" },
      { name: "Teams", amount: 659, billingCycle: "MONTHLY" },
      { name: "Teams", amount: 6590, billingCycle: "YEARLY" },
    ],
  },
  {
    name: "GitHub Copilot",
    logo: "https://www.google.com/s2/favicons?domain=github.com&sz=128",
    category: "Developer",
    plans: [
      { name: "Individual", amount: 899, billingCycle: "MONTHLY" },
      { name: "Individual", amount: 8999, billingCycle: "YEARLY" },
      { name: "Business", amount: 1599, billingCycle: "MONTHLY" },
      { name: "Enterprise", amount: 3299, billingCycle: "MONTHLY" },
    ],
  },
  {
    name: "Microsoft 365",
    logo: "https://www.google.com/s2/favicons?domain=microsoft365.com&sz=128",
    category: "Productivity",
    plans: [
      { name: "Personal", amount: 489, billingCycle: "MONTHLY" },
      { name: "Personal", amount: 4899, billingCycle: "YEARLY" },
      { name: "Family", amount: 619, billingCycle: "MONTHLY" },
      { name: "Family", amount: 6199, billingCycle: "YEARLY" },
    ],
  },
  {
    name: "Google One",
    logo: "https://cdn.simpleicons.org/google/4285F4",
    category: "Cloud Storage",
    plans: [
      { name: "100GB", amount: 130, billingCycle: "MONTHLY" },
      { name: "100GB", amount: 1300, billingCycle: "YEARLY" },
      { name: "200GB", amount: 210, billingCycle: "MONTHLY" },
      { name: "200GB", amount: 2100, billingCycle: "YEARLY" },
      { name: "2TB", amount: 650, billingCycle: "MONTHLY" },
      { name: "2TB", amount: 6500, billingCycle: "YEARLY" },
    ],
  },
  {
    name: "iCloud+",
    logo: "https://cdn.simpleicons.org/icloud/3693F3",
    category: "Cloud Storage",
    plans: [
      { name: "50GB", amount: 75, billingCycle: "MONTHLY" },
      { name: "200GB", amount: 219, billingCycle: "MONTHLY" },
      { name: "2TB", amount: 749, billingCycle: "MONTHLY" },
      { name: "6TB", amount: 2999, billingCycle: "MONTHLY" },
      { name: "12TB", amount: 5900, billingCycle: "MONTHLY" },
    ],
  },
  {
    name: "Notion",
    logo: "https://www.google.com/s2/favicons?domain=notion.so&sz=128",
    category: "Productivity",
    plans: [
      { name: "Plus", amount: 899, billingCycle: "MONTHLY" },
      { name: "Plus", amount: 8999, billingCycle: "YEARLY" },
      { name: "Business", amount: 1599, billingCycle: "MONTHLY" },
      { name: "Business", amount: 15999, billingCycle: "YEARLY" },
    ],
  },
  {
    name: "Dropbox",
    logo: "https://www.google.com/s2/favicons?domain=dropbox.com&sz=128",
    category: "Cloud Storage",
    plans: [
      { name: "Plus", amount: 999, billingCycle: "MONTHLY" },
      { name: "Plus", amount: 9999, billingCycle: "YEARLY" },
      { name: "Professional", amount: 1699, billingCycle: "MONTHLY" },
      { name: "Professional", amount: 16999, billingCycle: "YEARLY" },
    ],
  },
  {
    name: "Slack",
    logo: "https://www.google.com/s2/favicons?domain=slack.com&sz=128",
    category: "Productivity",
    plans: [
      { name: "Pro", amount: 749, billingCycle: "MONTHLY" },
      { name: "Pro", amount: 7499, billingCycle: "YEARLY" },
      { name: "Business+", amount: 1299, billingCycle: "MONTHLY" },
      { name: "Business+", amount: 12999, billingCycle: "YEARLY" },
    ],
  },
] as const;